// This file is auto-generated by @hey-api/openapi-ts

export type AuthenticatedUserRequest = {
  nickname: string
}

export type AuthenticationLogResource = {
  id: number
  ip_address: string | null
  user_agent: string | null
  successful: boolean
  created_at: string | null
  user?: UserResource
  ip?: IpResource
}

export type IpRequest = {
  address: string
  status: IpStatus
  remark?: string | null
}

export type IpResource = {
  id: number
  address: string
  location: LocationResource
  status: string
  remark: string | null
  created_at: string | null
  request_logs?: Array<RequestLogResource>
  authentication_logs?: Array<AuthenticationLogResource>
}

export type IpStatus = 1 | 2 | 10

export type LocationResource = {
  country_code: string
  timezone: string
  continent: string
  region: string
  city: string
}

export type LoginRequest = {
  username: string
  password: string
}

export type RequestLogResource = {
  id: number
  uuid: string
  ip_address: string | null
  method: string | null
  path: string | null
  headers: Array<unknown> | null
  payload: Array<unknown> | null
  response_status: number | null
  response_headers: Array<unknown> | null
  response: Array<unknown> | null
  duration: number | null
  memory: string
  created_at: string | null
  user?: UserResource
  ip?: IpResource
}

export type RoleResource = {
  value: string
  label: string
}

export type UserRequest = {
  username: string
  nickname: string
  mobile: string
  role: UserRole
  password: string
  status: UserStatus
}

export type UserResource = {
  id: number
  username: string
  nickname: string | null
  avatar: string | null
  mobile: string | null
  timezone: string | null
  role: string
  status: string
  created_at: string | null
}

export type UserRole = 1 | 2 | 10

export type UserStatus = 0 | 1 | 2 | 10 | 11

export type AdminLoginData = {
  body: LoginRequest
  path?: never
  query?: never
  url: '/login'
}

export type AdminLoginErrors = {
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminLoginError = AdminLoginErrors[keyof AdminLoginErrors]

export type AdminLoginResponses = {
  /**
   * `UserResource`
   */
  200: {
    data: UserResource
    meta: {
      token: string
    }
  }
}

export type AdminLoginResponse = AdminLoginResponses[keyof AdminLoginResponses]

export type AdminLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/logout'
}

export type AdminLogoutErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminLogoutError = AdminLogoutErrors[keyof AdminLogoutErrors]

export type AdminLogoutResponses = {
  /**
   * No content
   */
  204: void
}

export type AdminLogoutResponse = AdminLogoutResponses[keyof AdminLogoutResponses]

export type AdminUserShowData = {
  body?: never
  path?: never
  query?: never
  url: '/user'
}

export type AdminUserShowErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminUserShowError = AdminUserShowErrors[keyof AdminUserShowErrors]

export type AdminUserShowResponses = {
  /**
   * `UserResource`
   */
  200: {
    data: UserResource
  }
}

export type AdminUserShowResponse = AdminUserShowResponses[keyof AdminUserShowResponses]

export type AdminUserUpdateData = {
  body: AuthenticatedUserRequest
  path?: never
  query?: never
  url: '/user'
}

export type AdminUserUpdateErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminUserUpdateError = AdminUserUpdateErrors[keyof AdminUserUpdateErrors]

export type AdminUserUpdateResponses = {
  /**
   * `UserResource`
   */
  200: {
    data: UserResource
  }
}

export type AdminUserUpdateResponse = AdminUserUpdateResponses[keyof AdminUserUpdateResponses]

export type AdminUserPasswordUpdateData = {
  body: {
    current_password: string
    password: string
    password_confirmation: string
  }
  path?: never
  query?: never
  url: '/user/password'
}

export type AdminUserPasswordUpdateErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminUserPasswordUpdateError = AdminUserPasswordUpdateErrors[keyof AdminUserPasswordUpdateErrors]

export type AdminUserPasswordUpdateResponses = {
  /**
   * `UserResource`
   */
  200: {
    data: UserResource
  }
}

export type AdminUserPasswordUpdateResponse = AdminUserPasswordUpdateResponses[keyof AdminUserPasswordUpdateResponses]

export type AdminAuthenticationLogsIndexData = {
  body?: never
  path?: never
  query?: {
    /**
     * Number of items per page.
     */
    per_page?: number
    /**
     * Current page
     */
    page?: number
  }
  url: '/authentication-logs'
}

export type AdminAuthenticationLogsIndexErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminAuthenticationLogsIndexError =
  AdminAuthenticationLogsIndexErrors[keyof AdminAuthenticationLogsIndexErrors]

export type AdminAuthenticationLogsIndexResponses = {
  /**
   * Paginated set of `AuthenticationLogResource`
   */
  200: {
    data: Array<AuthenticationLogResource>
    meta: {
      current_page: number
      from: number | null
      last_page: number
      /**
       * Generated paginator links.
       */
      links: Array<{
        url: string | null
        label: string
        active: boolean
      }>
      /**
       * Base path for paginator generated URLs.
       */
      path: string | null
      /**
       * Number of items shown per page.
       */
      per_page: number
      /**
       * Number of the last item in the slice.
       */
      to: number | null
      /**
       * Total number of items being paginated.
       */
      total: number
    }
    links: {
      first: string | null
      last: string | null
      prev: string | null
      next: string | null
    }
  }
}

export type AdminAuthenticationLogsIndexResponse =
  AdminAuthenticationLogsIndexResponses[keyof AdminAuthenticationLogsIndexResponses]

export type AdminAuthenticationLogsShowData = {
  body?: never
  path: {
    /**
     * The authentication log ID
     */
    authenticationLog: number
  }
  query?: never
  url: '/authentication-logs/{authenticationLog}'
}

export type AdminAuthenticationLogsShowErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminAuthenticationLogsShowError =
  AdminAuthenticationLogsShowErrors[keyof AdminAuthenticationLogsShowErrors]

export type AdminAuthenticationLogsShowResponses = {
  /**
   * `AuthenticationLogResource`
   */
  200: {
    data: AuthenticationLogResource
  }
}

export type AdminAuthenticationLogsShowResponse =
  AdminAuthenticationLogsShowResponses[keyof AdminAuthenticationLogsShowResponses]

export type AdminDashboardData = {
  body?: never
  path?: never
  query?: never
  url: '/dashboard'
}

export type AdminDashboardErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminDashboardError = AdminDashboardErrors[keyof AdminDashboardErrors]

export type AdminDashboardResponses = {
  200: Array<string>
}

export type AdminDashboardResponse = AdminDashboardResponses[keyof AdminDashboardResponses]

export type AdminIpsIndexData = {
  body?: never
  path?: never
  query?: {
    /**
     * Number of items per page.
     */
    per_page?: number
    /**
     * Current page
     */
    page?: number
    /**
     * Field to sort by
     */
    sort?: string
    /**
     * Filter by username
     */
    'filter[address]'?: string
    /**
     * Filter by status
     */
    'filter[status]'?: string
  }
  url: '/ips'
}

export type AdminIpsIndexErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminIpsIndexError = AdminIpsIndexErrors[keyof AdminIpsIndexErrors]

export type AdminIpsIndexResponses = {
  /**
   * Paginated set of `IpResource`
   */
  200: {
    data: Array<IpResource>
    meta: {
      current_page: number
      from: number | null
      last_page: number
      /**
       * Generated paginator links.
       */
      links: Array<{
        url: string | null
        label: string
        active: boolean
      }>
      /**
       * Base path for paginator generated URLs.
       */
      path: string | null
      /**
       * Number of items shown per page.
       */
      per_page: number
      /**
       * Number of the last item in the slice.
       */
      to: number | null
      /**
       * Total number of items being paginated.
       */
      total: number
    }
    links: {
      first: string | null
      last: string | null
      prev: string | null
      next: string | null
    }
  }
}

export type AdminIpsIndexResponse = AdminIpsIndexResponses[keyof AdminIpsIndexResponses]

export type AdminIpsStoreData = {
  body: IpRequest
  path?: never
  query?: never
  url: '/ips'
}

export type AdminIpsStoreErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminIpsStoreError = AdminIpsStoreErrors[keyof AdminIpsStoreErrors]

export type AdminIpsStoreResponses = {
  /**
   * `IpResource`
   */
  200: {
    data: IpResource
  }
}

export type AdminIpsStoreResponse = AdminIpsStoreResponses[keyof AdminIpsStoreResponses]

export type AdminIpsDestroyData = {
  body?: never
  path: {
    /**
     * The ip ID
     */
    ip: number
  }
  query?: never
  url: '/ips/{ip}'
}

export type AdminIpsDestroyErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminIpsDestroyError = AdminIpsDestroyErrors[keyof AdminIpsDestroyErrors]

export type AdminIpsDestroyResponses = {
  /**
   * No content
   */
  204: void
}

export type AdminIpsDestroyResponse = AdminIpsDestroyResponses[keyof AdminIpsDestroyResponses]

export type AdminIpsShowData = {
  body?: never
  path: {
    /**
     * The ip ID
     */
    ip: number
  }
  query?: never
  url: '/ips/{ip}'
}

export type AdminIpsShowErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminIpsShowError = AdminIpsShowErrors[keyof AdminIpsShowErrors]

export type AdminIpsShowResponses = {
  /**
   * `IpResource`
   */
  200: {
    data: IpResource
  }
}

export type AdminIpsShowResponse = AdminIpsShowResponses[keyof AdminIpsShowResponses]

export type AdminIpsUpdateData = {
  body: IpRequest
  path: {
    /**
     * The ip ID
     */
    ip: number
  }
  query?: never
  url: '/ips/{ip}'
}

export type AdminIpsUpdateErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminIpsUpdateError = AdminIpsUpdateErrors[keyof AdminIpsUpdateErrors]

export type AdminIpsUpdateResponses = {
  /**
   * `IpResource`
   */
  200: {
    data: IpResource
  }
}

export type AdminIpsUpdateResponse = AdminIpsUpdateResponses[keyof AdminIpsUpdateResponses]

export type AdminRequestLogsIndexData = {
  body?: never
  path?: never
  query?: {
    /**
     * Number of items per page.
     */
    per_page?: number
    /**
     * Current page
     */
    page?: number
  }
  url: '/request-logs'
}

export type AdminRequestLogsIndexErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminRequestLogsIndexError = AdminRequestLogsIndexErrors[keyof AdminRequestLogsIndexErrors]

export type AdminRequestLogsIndexResponses = {
  /**
   * Paginated set of `RequestLogResource`
   */
  200: {
    data: Array<RequestLogResource>
    meta: {
      current_page: number
      from: number | null
      last_page: number
      /**
       * Generated paginator links.
       */
      links: Array<{
        url: string | null
        label: string
        active: boolean
      }>
      /**
       * Base path for paginator generated URLs.
       */
      path: string | null
      /**
       * Number of items shown per page.
       */
      per_page: number
      /**
       * Number of the last item in the slice.
       */
      to: number | null
      /**
       * Total number of items being paginated.
       */
      total: number
    }
    links: {
      first: string | null
      last: string | null
      prev: string | null
      next: string | null
    }
  }
}

export type AdminRequestLogsIndexResponse = AdminRequestLogsIndexResponses[keyof AdminRequestLogsIndexResponses]

export type AdminRequestLogsShowData = {
  body?: never
  path: {
    /**
     * The request log ID
     */
    requestLog: string
  }
  query?: never
  url: '/request-logs/{requestLog}'
}

export type AdminRequestLogsShowErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminRequestLogsShowError = AdminRequestLogsShowErrors[keyof AdminRequestLogsShowErrors]

export type AdminRequestLogsShowResponses = {
  /**
   * `RequestLogResource`
   */
  200: {
    data: RequestLogResource
  }
}

export type AdminRequestLogsShowResponse = AdminRequestLogsShowResponses[keyof AdminRequestLogsShowResponses]

export type AdminRolesIndexData = {
  body?: never
  path?: never
  query?: never
  url: '/roles'
}

export type AdminRolesIndexErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminRolesIndexError = AdminRolesIndexErrors[keyof AdminRolesIndexErrors]

export type AdminRolesIndexResponses = {
  /**
   * Array of `RoleResource`
   */
  200: {
    data: Array<RoleResource>
  }
}

export type AdminRolesIndexResponse = AdminRolesIndexResponses[keyof AdminRolesIndexResponses]

export type AdminUsersIndexData = {
  body?: never
  path?: never
  query?: {
    /**
     * Number of items per page.
     */
    per_page?: number
    /**
     * Current page
     */
    page?: number
    /**
     * Field to sort by
     */
    sort?: string
    /**
     * Filter by username
     */
    'filter[username]'?: string
    /**
     * Filter by nickname
     */
    'filter[nickname]'?: string
    /**
     * Filter by status
     */
    'filter[status]'?: string
  }
  url: '/users'
}

export type AdminUsersIndexErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminUsersIndexError = AdminUsersIndexErrors[keyof AdminUsersIndexErrors]

export type AdminUsersIndexResponses = {
  /**
   * Paginated set of `UserResource`
   */
  200: {
    data: Array<UserResource>
    meta: {
      current_page: number
      from: number | null
      last_page: number
      /**
       * Generated paginator links.
       */
      links: Array<{
        url: string | null
        label: string
        active: boolean
      }>
      /**
       * Base path for paginator generated URLs.
       */
      path: string | null
      /**
       * Number of items shown per page.
       */
      per_page: number
      /**
       * Number of the last item in the slice.
       */
      to: number | null
      /**
       * Total number of items being paginated.
       */
      total: number
    }
    links: {
      first: string | null
      last: string | null
      prev: string | null
      next: string | null
    }
  }
}

export type AdminUsersIndexResponse = AdminUsersIndexResponses[keyof AdminUsersIndexResponses]

export type AdminUsersStoreData = {
  body: UserRequest
  path?: never
  query?: never
  url: '/users'
}

export type AdminUsersStoreErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminUsersStoreError = AdminUsersStoreErrors[keyof AdminUsersStoreErrors]

export type AdminUsersStoreResponses = {
  /**
   * `UserResource`
   */
  201: {
    data: UserResource
  }
}

export type AdminUsersStoreResponse = AdminUsersStoreResponses[keyof AdminUsersStoreResponses]

export type AdminUsersDestroyData = {
  body?: never
  path: {
    /**
     * The user ID
     */
    user: number
  }
  query?: never
  url: '/users/{user}'
}

export type AdminUsersDestroyErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminUsersDestroyError = AdminUsersDestroyErrors[keyof AdminUsersDestroyErrors]

export type AdminUsersDestroyResponses = {
  /**
   * No content
   */
  204: void
}

export type AdminUsersDestroyResponse = AdminUsersDestroyResponses[keyof AdminUsersDestroyResponses]

export type AdminUsersShowData = {
  body?: never
  path: {
    /**
     * The user ID
     */
    user: number
  }
  query?: never
  url: '/users/{user}'
}

export type AdminUsersShowErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
}

export type AdminUsersShowError = AdminUsersShowErrors[keyof AdminUsersShowErrors]

export type AdminUsersShowResponses = {
  /**
   * `UserResource`
   */
  200: {
    data: UserResource
  }
}

export type AdminUsersShowResponse = AdminUsersShowResponses[keyof AdminUsersShowResponses]

export type AdminUsersUpdateData = {
  body: UserRequest
  path: {
    /**
     * The user ID
     */
    user: number
  }
  query?: never
  url: '/users/{user}'
}

export type AdminUsersUpdateErrors = {
  /**
   * Unauthenticated
   */
  401: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Authorization error
   */
  403: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Not found
   */
  404: {
    /**
     * Error overview.
     */
    message: string
  }
  /**
   * Validation error
   */
  422: {
    /**
     * Errors overview.
     */
    message: string
    /**
     * A detailed description of each field that failed validation.
     */
    errors: {
      [key: string]: Array<string>
    }
  }
}

export type AdminUsersUpdateError = AdminUsersUpdateErrors[keyof AdminUsersUpdateErrors]

export type AdminUsersUpdateResponses = {
  /**
   * `UserResource`
   */
  200: {
    data: UserResource
  }
}

export type AdminUsersUpdateResponse = AdminUsersUpdateResponses[keyof AdminUsersUpdateResponses]

export type ClientOptions = {
  baseUrl: 'http://laravel-skeleton.test/api/admin' | (string & {})
}
